include: package:lints/recommended.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - directives_ordering
    - always_declare_return_types
    - omit_local_variable_types
    - prefer_final_locals
    - unnecessary_this
    - prefer_if_null_operators
    - prefer_const_constructors
